apiVersion: batch/v1
kind: Job
metadata:
  name: pithos-delete-backup-bucket
spec:
  template:
    metadata:
      name: pithos-delete-backup-bucket
    spec:
      restartPolicy: OnFailure
      containers:
        - image: pithos-jobs:latest
          name: pithos-delete-backup-bucket
          command: ["/entrypoint.sh"]
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: pithos-keys
                  key: tenant.key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: pithos-keys
                  key: tenant.secret
            - name: PITHOS_S3_ENDPOINT
              value: "pithos.default.svc"
            - name: PITHOS_BACKUP_BUCKET
              value: "stolon-backup"
          volumeMounts:
            - name: cluster-ca
              mountPath: /etc/ssl/cluster-ca
      volumes:
        - name: cluster-ca
          secret:
            secretName: cluster-ca
